# Generated by Django 5.0.6 on 2024-07-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Packing_List',
            new_name='List',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='packing_list',
            new_name='list_id',
        ),
        migrations.RenameField(
            model_name='list',
            old_name='trip',
            new_name='trip_id',
        ),
        migrations.AddField(
            model_name='item',
            name='is_packed',
            field=models.BooleanField(default=0),
        ),
    ]
